yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.deletion import SET_NULL

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Class Group."""

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """Class Post."""

    text = models.TextField("Текст поста", help_text="Введите текст поста")
    pub_date = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )
    image = models.ImageField(
        "Изображение",
        upload_to="posts/",
        blank=True,
        help_text="Изображение к посту",
    )

    class Meta:
        ordering = ("-pub_date",)

    def __str__(self) -> str:
        return self.text


class Comment(CreatedModel):
    """Class Comment."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="text",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField(
        "Текст комментария", help_text="Текст нового комментария"
    )


class Follow(CreatedModel):
    """Class Follow."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Пользователь",
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name="unique_following",
                fields=["user", "author"]
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Class Create/Edit Post Form."""

    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )


class CommentForm(forms.ModelForm):
    """Class Create Comment Form."""

    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Subquery
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator


def index(request):
    """Start page."""

    page_obj = paginator(request, Post.objects.select_related("group").all())

    context = {
        "title": "Последние обновления на сайте",
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    """Group list page."""

    group = get_object_or_404(Group, slug=slug)
    page_obj = paginator(request, group.posts.all())

    context = {
        "group": group,
        "page_obj": page_obj,
        "title": f"Записи сообщества {group.title}",
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    """Profile page."""

    author = get_object_or_404(User, username=username)
    page_obj = paginator(
        request, Post.objects.filter(author__username=username)
    )
    following = True

    if request.user.is_authenticated:
        author_in: bool = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
        if not author_in:
            following = False

    context = {"author": author, "page_obj": page_obj, "following": following}
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    """Post detail page."""

    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()

    context = {"form": CommentForm(), "post": post, "comments": comments}
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    """Creating post page."""

    form = PostForm(request.POST or None, files=request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author.username)

    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, post_id):
    """Editing post page."""

    post_ed = get_object_or_404(Post, pk=post_id)

    if post_ed.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post_ed
    )

    if form.is_valid():
        post_ed.save()
        return redirect("posts:post_detail", post_id=post_id)

    context = {"form": form, "is_edit": True}
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    """Add a comment."""

    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    """Show page with following authors."""

    authors = Follow.objects.filter(user=request.user)
    posts_list = Post.objects.filter(
        author_id__in=Subquery(authors.values("author_id"))
    )
    page_obj = paginator(request, posts_list)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    """Subscribe to author."""

    author = get_object_or_404(User, username=username)
    if request.user == author:
        return redirect("posts:profile", username=username)
    Follow.objects.get_or_create(author=author, user=request.user)

    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    """Unsubscribe to author."""

    author = get_object_or_404(User, username=username)
    Follow.objects.filter(author=author, user=request.user).delete()

    return redirect("posts:profile", username=username)

yatube/templates/posts/includes/paginator.html
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-auto" >
            {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation" class="my-5">
                <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        Предыдущая
                    </a>
                    </li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        Следующая
                    </a>
                    </li>
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                        Последняя
                    </a>
                    </li>
                {% endif %}    
                </ul>
            </nav>
            {% endif %}        
        </div>
    </div>
</div> 

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}
 

yatube/templates/posts/includes/thumbnail.html
{% load thumbnail %} 
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}